Code submission for section leader review
denwychan/ngrams pull request #1
Opened 2022-08-27 15:39 UTC by denwychan

2022-09-12 11:29 UTC, justinsalloum requested changes
Very nicely done! The only thing that needs fixing is the logic to generate the grammar map, but apart from that the functionality, decomposition and choices of data structures are all excellent. I made a few comments and suggestions on minor style improvements and some possible optimisations and opportunities to simplify the syntax.

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +    // Instatiate a vector for the word tokens form the text file and a map for the Ngrams
```suggestion
    // Instatiate a vector for the word tokens from the text file and a map for the Ngrams

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +                "Input file name? ","Unable to open that file. Try again.");
```suggestion
                "Input file name? ", "Unable to open that file. Try again.");

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +                    bool exitWhen0) {
Nit: maybe rename this boolean to `exitWhenZero`? It might make it easier to read

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +            if (userInput == 0) {
You can condense these two conditions into one. I.e. `if (exitWhenZero && userInput == 0)`

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> + * Function: getNGRamsMap
```suggestion
 * Function: getNGramsMap

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> + * Usage:Creates a map of the n-grams of words as the key and the following word as a value
The values are actually a list of words (not a single word), so you can update this comment as per suggestion:

```suggestion
 * Usage:Creates a map of the n-grams of words as the key and the following words as a value

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +        Vector<string> window(1, tokenVec.get(i));
This type of initialisation syntax is more useful when the first paramater is a number greater than 1, as it initialises a vector with n elements of the same value. Suggested alternative syntax that is simpler for your use case:
```suggestion
        Vector<string> window {tokenVec.get(i)};

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +        Vector<string> window(1, tokenVec.get(i));
You can also use the `[]` syntax to get values from a vector. Same as map and grid. Not necessary to change it here, but just reminding you that options :)

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +        string randWord = map.get(startKey)[randIndex];
You can reuse the `valueVec` variable instead of looking up in the map a second time.
```suggestion
        string randWord = valueVec[randIndex];

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +        Vector<string> tokenValue;
Creating a new `tokenValue` vector every time will mean that all the values in your map will be vectors of size 1! What we really want to do instead is get the existing vector value from the map with the corresponding key and add the word to that vector. An example of shorthand syntax for this is:
```
map[key] += word;
```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +     for (int i = 0; i < tokenVec.size(); i++) {
Suggestion for this overall logic: rather than nesting the two for loops inside each other and building up the window from scratch every time, you can start by building up an initial window [1], then do your loop that iterates over `tokenVec` [2] and inside of that loop you can "slide" the window by adding a new word to the end and removing the first element [3].

1. 
```
Vector<string> window;
for (int i = 0; i < n - 1; i++) {
    window.add(tokenVec.get(i % tokenVec.size())); // Use mod for the index so the tokens
            // can wrap around the text
}
```

2.
```
for (int i = 0; i < tokenVec.size(); i++ ) {
    ... add word to vector value in map
   ... adjust window
}
```

3.
```
// Example of how to slide a window:
window += newElement;
window.remove(0);
```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +void getNGramsMap(Map<Vector<string>, Vector<string>> &map, const Vector<string> &tokenVec, int n) {
Quick note on this function: N-grams actually means keys of size N - 1. The example in your comment is actually a 3-gram. So you just need to do one fewer iteration to build your window.

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +        randomText.add(key);
Alternative shorthand:
```suggestion
        randomText += key;

```

2022-09-12 11:29 UTC, justinsalloum commented on src/ngrams.cpp
> +    while (randomText.size() != numWordsToGen) {
Since this is a fixed number of iterations, I'd recommend using a for loop here instead of a while loop.

2022-09-12 15:31 UTC, denwychan commented on src/ngrams.cpp
> +        startKey.add(randWord);
Add before removing in case the collection is empty

2022-09-14 15:54 UTC, denwychan commented on src/ngrams.cpp
> +            if (userInput == 0) {
Good catch!

2022-09-14 15:59 UTC, denwychan commented on src/ngrams.cpp
> +        Vector<string> window(1, tokenVec.get(i));
Updated!

2022-09-14 21:46 UTC, justinsalloum approved these changes
LGTM - it's much cleaner now! And now the grammar map is being generated correctly :)

2022-09-14 21:48 UTC, merged